/**
 * Razorpay payment handler.
 * Expects a real Razorpay order_id generated by the backend.
 */
export function initiateRazorpayPayment({
  amount,       // in paise (INR * 100)
  currency = "INR",
  razorpayOrderId, // real order_id from Razorpay backend API
  customerName,
  customerEmail,
  customerPhone,
  description = "M'Couture Order",
}) {
  return new Promise((resolve, reject) => {
    const keyId = import.meta.env.VITE_RAZORPAY_KEY_ID;

    // Demo mode when no real key is configured
    if (!keyId || keyId === "rzp_test_your_key_here" || keyId === "") {
      console.warn("[Razorpay] No key configured — using demo mode");
      setTimeout(() => {
        resolve({
          razorpay_payment_id: `demo_pay_${Date.now()}`,
          razorpay_order_id: razorpayOrderId || `demo_order_${Date.now()}`,
          razorpay_signature: "demo_signature",
          demo: true,
        });
      }, 1000);
      return;
    }

    if (typeof window.Razorpay === "undefined") {
      reject(new Error("Razorpay SDK not loaded. Check your internet connection."));
      return;
    }

    const options = {
      key: keyId,
      amount,
      currency,
      name: "M'Couture",
      description,
      order_id: razorpayOrderId,
      prefill: {
        name: customerName || "",
        email: customerEmail || "",
        contact: customerPhone || "",
      },
      theme: {
        color: "#C8A96A",
      },
      handler: (response) => {
        resolve(response);
      },
      modal: {
        ondismiss: () => {
          reject(new Error("Payment cancelled"));
        },
      },
    };

    const rzp = new window.Razorpay(options);
    rzp.open();
  });
}
