/**
 * Dynamically loads the Razorpay checkout script on demand.
 * Idempotent — safe to call multiple times; resolves instantly if already loaded.
 */
function loadRazorpayScript() {
  return new Promise((resolve, reject) => {
    if (typeof window.Razorpay !== "undefined") {
      resolve(); // already loaded
      return;
    }
    const existing = document.querySelector('script[src*="checkout.razorpay.com"]');
    if (existing) {
      existing.addEventListener("load", resolve);
      existing.addEventListener("error", reject);
      return;
    }
    const script = document.createElement("script");
    script.src = "https://checkout.razorpay.com/v1/checkout.js";
    script.async = true;
    script.onload = resolve;
    script.onerror = () => reject(new Error("Failed to load Razorpay SDK"));
    document.head.appendChild(script);
  });
}

/**
 * Razorpay payment handler.
 * Expects a real Razorpay order_id generated by the backend.
 */
export async function initiateRazorpayPayment({
  amount,       // in paise (INR * 100)
  currency = "INR",
  razorpayOrderId, // real order_id from Razorpay backend API
  customerName,
  customerEmail,
  customerPhone,
  description = "M'Couture Order",
}) {
  const keyId = import.meta.env.VITE_RAZORPAY_KEY_ID;

  // Demo mode when no real key is configured
  if (!keyId || keyId === "rzp_test_your_key_here" || keyId === "") {
    console.warn("[Razorpay] No key configured — using demo mode");
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({
          razorpay_payment_id: `demo_pay_${Date.now()}`,
          razorpay_order_id: razorpayOrderId || `demo_order_${Date.now()}`,
          razorpay_signature: "demo_signature",
          demo: true,
        });
      }, 1000);
    });
  }

  // Ensure the Razorpay SDK is loaded before using it
  try {
    await loadRazorpayScript();
  } catch {
    throw new Error("Razorpay SDK failed to load. Check your internet connection.");
  }

  if (!razorpayOrderId) {
    throw new Error("Could not reach payment server. Please try again in a moment.");
  }

  return new Promise((resolve, reject) => {
    const options = {
      key: keyId,
      amount,
      currency,
      name: "M'Couture",
      description,
      order_id: razorpayOrderId,
      prefill: {
        name: customerName || "",
        email: customerEmail || "",
        contact: customerPhone || "",
      },
      theme: {
        color: "#C8A96A",
      },
      handler: (response) => {
        resolve(response);
      },
      modal: {
        ondismiss: () => {
          reject(new Error("Payment cancelled"));
        },
      },
    };

    const rzp = new window.Razorpay(options);
    rzp.open();
  });
}
